In [1]:
!pip install pandas numpy matplotlib seaborn plotly fastapi uvicorn sqlalchemy psycopg2-binary python-jose passlib bcrypt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.138.0)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.49.0)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.51)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Collecting python-jose
  Downloading python_jose-3.5.0-py2.py3-none-any.whl.metadata (5.5 kB)
Collecting passlib
  Downloading passlib-1.7.4-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting bcrypt
  Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.4.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.5.2)
Collecting ecdsa!=0.15 (from python-jose)
  Downloading ecdsa-0.19.2-py2.py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: rsa!=4.1.1,!=4.4,<5.0,>=4.0 in /usr/local/lib/python3.12/dist-packages (from python-jose) (4.9.1)
Requirement already satisfied: pyasn1>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from python-jose) (0.6.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from ecdsa!=0.15->python-jose) (1.17.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.18)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 13.4 MB/s eta 0:00:00
Downloading python_jose-3.5.0-py2.py3-none-any.whl (34 kB)
Downloading passlib-1.7.4-py2.py3-none-any.whl (525 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 525.6/525.6 kB 43.1 MB/s eta 0:00:00
Downloading bcrypt-5.0.0-cp39-abi3-manylinux_2_34_x86_64.whl (278 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 23.0 MB/s eta 0:00:00
Downloading ecdsa-0.19.2-py2.py3-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.8/150.8 kB 17.5 MB/s eta 0:00:00
Installing collected packages: passlib, psycopg2-binary, ecdsa, bcrypt, python-jose
Successfully installed bcrypt-5.0.0 ecdsa-0.19.2 passlib-1.7.4 psycopg2-binary-2.9.12 python-jose-3.5.0

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from datetime import datetime, timedelta

import warnings
warnings.filterwarnings("ignore")

In [3]:
np.random.seed(42)


services = [
    "Salesforce",
    "Slack",
    "ServiceNow",
    "Workday",
    "SAP",
    "Stripe"
]


endpoints = [
    "/users",
    "/payments",
    "/transactions",
    "/customers",
    "/orders",
    "/reports"
]


methods = [
    "GET",
    "POST",
    "PUT",
    "DELETE"
]


roles = [
    "admin",
    "developer",
    "analyst",
    "viewer"
]


regions = [
    "us-east-1",
    "us-west-2",
    "eu-central-1"
]


records = []


for i in range(25000):

    timestamp = datetime.now() - timedelta(
        minutes=np.random.randint(1,50000)
    )

    status = np.random.choice(
        [200,201,400,401,403,404,500],
        p=[0.70,0.10,0.05,0.04,0.04,0.03,0.04]
    )


    records.append({

        "request_id":i+10000,

        "service_name":
        np.random.choice(services),

        "endpoint":
        np.random.choice(endpoints),

        "method":
        np.random.choice(methods),

        "response_time_ms":
        np.random.randint(20,1500),

        "status_code":
        status,

        "user_role":
        np.random.choice(roles),

        "region":
        np.random.choice(regions),

        "payload_size_kb":
        np.random.randint(1,500),

        "timestamp":
        timestamp
    })


df=pd.DataFrame(records)

df.head()

,request_id,service_name,endpoint,method,response_time_ms,status_code,user_role,region,payload_size_kb,timestamp
0,10000,ServiceNow,/orders,GET,141,404,analyst,eu-central-1,331,2026-07-04 14:49:57.725001
1,10001,Workday,/transactions,POST,1352,401,developer,us-west-2,294,2026-06-30 08:02:57.725321
2,10002,SAP,/users,DELETE,1357,200,developer,us-east-1,236,2026-07-13 21:31:57.725468
3,10003,ServiceNow,/payments,DELETE,719,200,viewer,eu-central-1,190,2026-06-26 12:04:57.727915
4,10004,Workday,/customers,DELETE,1174,200,admin,eu-central-1,135,2026-07-02 07:26:57.728051

In [4]:
df.to_csv(
    "api_logs.csv",
    index=False
)

print(
    "Dataset Created:",
    df.shape
)

Dataset Created: (25000, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   request_id        25000 non-null  int64
 1   service_name      25000 non-null  object
 2   endpoint          25000 non-null  object
 3   method            25000 non-null  object
 4   response_time_ms  25000 non-null  int64
 5   status_code       25000 non-null  int64
 6   user_role         25000 non-null  object
 7   region            25000 non-null  object
 8   payload_size_kb   25000 non-null  int64
 9   timestamp         25000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 1.9+ MB

In [6]:
df.isnull().sum()

request_id          0
service_name        0
endpoint            0
method              0
response_time_ms    0
status_code         0
user_role           0
region              0
payload_size_kb     0
timestamp           0
dtype: int64

In [7]:
df.describe()

,request_id,response_time_ms,status_code,payload_size_kb,timestamp
count,25000.000000,25000.000000,25000.000000,25000.000000,25000
mean,22499.500000,759.457880,244.790560,248.816200,2026-06-28 05:02:03.115724288
min,10000.000000,20.000000,200.000000,1.000000,2026-06-10 20:47:58.047210
25%,16249.750000,392.750000,200.000000,125.000000,2026-06-19 12:14:44.397126400
50%,22499.500000,760.500000,200.000000,247.000000,2026-06-28 06:08:58.932884480
75%,28749.250000,1129.000000,201.000000,374.000000,2026-07-06 21:04:12.940909312
max,34999.000000,1499.000000,500.000000,499.000000,2026-07-15 14:03:59.102460
std,7217.022701,425.795892,90.668393,143.863639,NaN

In [8]:
traffic = (
    df.groupby("service_name")
    .size()
    .reset_index(name="requests")
)


fig = px.bar(
    traffic,
    x="service_name",
    y="requests",
    title="API Request Volume by SaaS Integration"
)

fig.show()

In [9]:
latency = (
    df.groupby("endpoint")
    ["response_time_ms"]
    .mean()
    .reset_index()
)


fig = px.bar(
    latency,
    x="endpoint",
    y="response_time_ms",
    title="Average API Latency"
)

fig.show()

In [10]:
df["error_flag"] = np.where(
    df["status_code"]>=400,
    1,
    0
)


errors = (
    df.groupby("service_name")
    ["error_flag"]
    .mean()
    .reset_index()
)


errors["error_rate"] = (
    errors["error_flag"]*100
)


fig = px.bar(
    errors,
    x="service_name",
    y="error_rate",
    title="API Failure Rate (%)"
)

fig.show()

In [11]:
health = (
    df.groupby("service_name")
    .agg(
        avg_latency=("response_time_ms","mean"),
        availability=("error_flag",
                       lambda x:
                       100*(1-x.mean()))
    )
    .reset_index()
)


health["health_score"] = (
    health["availability"]*0.7
    -
    health["avg_latency"]/100*0.3
)


health

  service_name  avg_latency  availability  health_score
0          SAP   763.219052     79.933978     53.664127
1   Salesforce   761.556922     79.985247     53.705002
2   ServiceNow   751.373039     80.539216     54.123332
3        Slack   762.191874     80.671677     54.183598
4       Stripe   753.586378     78.364365     52.594296
5      Workday   764.753345     79.615665     53.436706

In [12]:
security = (
    df.groupby(
        ["user_role","status_code"]
    )
    .size()
    .reset_index(
        name="requests"
    )
)


fig=px.sunburst(
    security,
    path=[
        "user_role",
        "status_code"
    ],
    values="requests",
    title="Authorization Failure Analysis"
)


fig.show()

In [13]:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base


DATABASE_URL = (
    "postgresql://postgres:password@localhost:5432/api_gateway"
)


engine = create_engine(
    DATABASE_URL
)


SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)


Base = declarative_base()



def get_db():

    db = SessionLocal()

    try:
        yield db

    finally:
        db.close()

In [15]:
import os

os.makedirs("backend/routers", exist_ok=True)

print("Backend structure created")

Backend structure created

In [16]:
%%writefile backend/database.py

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, declarative_base


DATABASE_URL = "sqlite:///./enterprise_gateway.db"


engine = create_engine(
    DATABASE_URL,
    connect_args={
        "check_same_thread": False
    }
)


SessionLocal = sessionmaker(
    autocommit=False,
    autoflush=False,
    bind=engine
)


Base = declarative_base()



def get_db():

    db = SessionLocal()

    try:
        yield db

    finally:
        db.close()

Writing backend/database.py

In [17]:
%%writefile backend/models.py

from sqlalchemy import Column,Integer,String

from database import Base



class User(Base):

    __tablename__="users"


    id = Column(
        Integer,
        primary_key=True,
        index=True
    )


    username = Column(
        String,
        unique=True
    )


    password = Column(
        String
    )


    role = Column(
        String
    )




class Integration(Base):

    __tablename__="integrations"


    id = Column(
        Integer,
        primary_key=True
    )


    name = Column(
        String
    )


    provider = Column(
        String
    )


    api_url = Column(
        String
    )


    status = Column(
        String
    )

Writing backend/models.py

In [18]:
import sys

sys.path.append("/content/backend")

In [19]:
from database import Base
from models import User, Integration

print("Import successful")

Import successful

In [21]:
from pydantic import BaseModel



class UserCreate(BaseModel):

    username:str
    password:str
    role:str



class IntegrationCreate(BaseModel):

    name:str
    provider:str
    api_url:str



class Token(BaseModel):

    access_token:str
    token_type:str

In [22]:
from datetime import datetime,timedelta

from jose import jwt

from passlib.context import CryptContext



SECRET_KEY="enterprise-secret-key"


ALGORITHM="HS256"



pwd_context = CryptContext(
    schemes=["bcrypt"],
    deprecated="auto"
)



def hash_password(password):

    return pwd_context.hash(
        password
    )



def verify_password(
    plain,
    hashed
):

    return pwd_context.verify(
        plain,
        hashed
    )



def create_token(data):

    payload=data.copy()


    payload["exp"]=(
        datetime.utcnow()
        +
        timedelta(minutes=60)
    )


    return jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM
    )

In [23]:
import secrets



API_KEYS={}



def generate_api_key():

    key = secrets.token_hex(32)

    API_KEYS[key]="active"


    return key



def validate_api_key(key):

    return (
        key in API_KEYS
        and
        API_KEYS[key]=="active"
    )

In [25]:
import sys

sys.path.append("/content/backend")

In [37]:
import os

print(os.listdir("/content/backend"))

['main.py', 'models.py', 'auth.py', '__pycache__', 'database.py', 'routers']

In [27]:
%%writefile backend/auth.py

from datetime import datetime, timedelta

from jose import jwt

from passlib.context import CryptContext



SECRET_KEY = "enterprise-secret-key"

ALGORITHM = "HS256"



pwd_context = CryptContext(
    schemes=["bcrypt"],
    deprecated="auto"
)



def hash_password(password):

    return pwd_context.hash(password)




def verify_password(
    plain_password,
    hashed_password
):

    return pwd_context.verify(
        plain_password,
        hashed_password
    )




def create_token(data):

    payload = data.copy()


    expire = (
        datetime.utcnow()
        +
        timedelta(minutes=60)
    )


    payload["exp"] = expire


    return jwt.encode(
        payload,
        SECRET_KEY,
        algorithm=ALGORITHM
    )

Writing backend/auth.py

In [28]:
!pip install python-jose passlib bcrypt

Requirement already satisfied: python-jose in /usr/local/lib/python3.12/dist-packages (3.5.0)
Requirement already satisfied: passlib in /usr/local/lib/python3.12/dist-packages (1.7.4)
Requirement already satisfied: bcrypt in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: ecdsa!=0.15 in /usr/local/lib/python3.12/dist-packages (from python-jose) (0.19.2)
Requirement already satisfied: rsa!=4.1.1,!=4.4,<5.0,>=4.0 in /usr/local/lib/python3.12/dist-packages (from python-jose) (4.9.1)
Requirement already satisfied: pyasn1>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from python-jose) (0.6.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from ecdsa!=0.15->python-jose) (1.17.0)

In [29]:
from auth import (
    hash_password,
    create_token
)

print("Auth module working")

Auth module working

In [30]:
import os

os.makedirs(
    "/content/backend/routers",
    exist_ok=True
)

open(
    "/content/backend/routers/__init__.py",
    "w"
).close()

print("Router package created")

Router package created

In [31]:
%%writefile backend/routers/users.py


from fastapi import APIRouter

from auth import (
    hash_password,
    create_token
)



router = APIRouter(
    prefix="/users",
    tags=["Users"]
)



users_db = []



@router.post("/register")
def register_user(
    username:str,
    password:str,
    role:str
):


    encrypted_password = hash_password(
        password
    )


    user = {

        "username": username,

        "password": encrypted_password,

        "role": role
    }


    users_db.append(user)


    return {

        "message":
        "User registered successfully",

        "user":
        username

    }




@router.post("/login")
def login_user(
    username:str
):


    token = create_token(
        {
            "username":
            username
        }
    )


    return {

        "access_token":
        token,

        "token_type":
        "bearer"

    }

Writing backend/routers/users.py

In [32]:
%%writefile backend/routers/integrations.py


from fastapi import APIRouter

from api_keys import (
    generate_api_key,
    validate_api_key
)



router = APIRouter(

    prefix="/integrations",

    tags=["SaaS Integrations"]

)



services=[]




@router.post("/connect")
def connect_application(

    application_name:str,

    provider:str,

    api_endpoint:str

):


    service={

        "application":
        application_name,


        "provider":
        provider,


        "endpoint":
        api_endpoint,


        "status":
        "Connected"

    }


    services.append(service)


    return service





@router.get("/")
def get_integrations():

    return {

        "total_integrations":
        len(services),

        "services":
        services

    }





@router.post("/generate-api-key")
def create_api_key():


    key = generate_api_key()


    return {

        "api_key":
        key

    }

Writing backend/routers/integrations.py

In [33]:
%%writefile backend/routers/analytics.py


from fastapi import APIRouter

import pandas as pd



router = APIRouter(

    prefix="/analytics",

    tags=["API Monitoring"]

)



@router.get("/service-health")


def service_health():


    df=pd.read_csv(
        "/content/api_logs.csv"
    )


    df["success"] = (
        df["status_code"]
        <400
    )



    result=(

        df.groupby(
            "service_name"
        )

        .agg(

            total_requests=
            ("request_id","count"),

            avg_latency=
            ("response_time_ms","mean"),

            uptime=
            ("success","mean")

        )

        .reset_index()

    )



    result["uptime_percentage"] = (

        result["uptime"]*100

    )



    return result.to_dict(
        orient="records"
    )

Writing backend/routers/analytics.py

In [34]:
%%writefile backend/main.py


from fastapi import FastAPI


from routers import (

    users,

    integrations,

    analytics

)



app = FastAPI(

    title=
    "Enterprise API Gateway Platform",

    description=
    """
    Enterprise SaaS Integration Platform

    Features:
    - OAuth2 Authentication
    - JWT Security
    - API Key Management
    - RBAC Authorization
    - API Monitoring
    """,

    version="1.0"

)



app.include_router(
    users.router
)


app.include_router(
    integrations.router
)


app.include_router(
    analytics.router
)



@app.get("/")
def home():

    return {

        "platform":
        "Enterprise API Gateway",

        "status":
        "Running"

    }

Writing backend/main.py

In [35]:
!pip install fastapi uvicorn nest_asyncio

Requirement already satisfied: fastapi in /usr/local/lib/python3.12/dist-packages (0.138.0)
Requirement already satisfied: uvicorn in /usr/local/lib/python3.12/dist-packages (0.49.0)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (1.3.1)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (2.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from fastapi) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi) (0.0.4)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (8.4.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.9.0->fastapi) (2.46.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette>=0.46.0->fastapi) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi) (3.18)

In [38]:
import os

print(os.listdir("/content/backend"))

['main.py', 'models.py', 'auth.py', '__pycache__', 'database.py', 'routers']

In [39]:
%%writefile backend/api_keys.py


import secrets


API_KEYS = {}



def generate_api_key():

    key = secrets.token_hex(32)

    API_KEYS[key] = "active"

    return key



def validate_api_key(key):

    return (
        key in API_KEYS
        and API_KEYS[key] == "active"
    )

Writing backend/api_keys.py

In [40]:
import sys
import os


sys.path.insert(
    0,
    "/content/backend"
)


sys.path.insert(
    0,
    "/content/backend/routers"
)


print(sys.path[:3])

['/content/backend/routers', '/content/backend', '/content']

In [41]:
from api_keys import (
    generate_api_key,
    validate_api_key
)


print("API Key Module Working")

print(
    generate_api_key()
)

API Key Module Working
4bc09787054d40a92a66a059ccb48d4e8593c00f7c4e267106c6f4e957a7ee30

In [42]:
from main import app

print(
    "FastAPI Loaded Successfully"
)

FastAPI Loaded Successfully

In [43]:
import sys

sys.path.append(
    "/content/backend"
)


import nest_asyncio

nest_asyncio.apply()



from main import app

print(
    "FastAPI Application Loaded Successfully"
)

FastAPI Application Loaded Successfully

In [1]:
!pip install "uvicorn<0.30" nest_asyncio

Requirement already satisfied: uvicorn<0.30 in /usr/local/lib/python3.12/dist-packages (0.29.0)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn<0.30) (8.4.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<0.30) (0.16.0)

In [2]:
import sys

sys.path.insert(
    0,
    "/content/backend"
)

from main import app

print("FastAPI app loaded")

FastAPI app loaded

In [3]:
import nest_asyncio
import uvicorn
import threading


nest_asyncio.apply()



def run_server():

    uvicorn.run(
        app,
        host="0.0.0.0",
        port=8000
    )


thread = threading.Thread(
    target=run_server
)


thread.start()

In [8]:
!pkill -f uvicorn

In [9]:
import os

for root, dirs, files in os.walk("/content/backend"):
    level = root.replace("/content/backend","").count(os.sep)
    indent = " "*4*level
    print(indent + os.path.basename(root) + "/")

    for file in files:
        print(indent+"    "+file)

backend/
    main.py
    models.py
    api_keys.py
    auth.py
    database.py
    __pycache__/
        main.cpython-312.pyc
        api_keys.cpython-312.pyc
        auth.cpython-312.pyc
        database.cpython-312.pyc
        models.cpython-312.pyc
    routers/
        __init__.py
        users.py
        integrations.py
        analytics.py
        __pycache__/
            analytics.cpython-312.pyc
            users.cpython-312.pyc
            integrations.cpython-312.pyc
            __init__.cpython-312.pyc

In [10]:
%%writefile backend/main.py

from fastapi import FastAPI

from routers.users import router as users_router
from routers.integrations import router as integrations_router
from routers.analytics import router as analytics_router


app = FastAPI(

    title="Enterprise API Gateway Platform",

    description="""
    Enterprise SaaS Integration Platform
    with JWT, OAuth2, API Keys,
    RBAC and API Monitoring
    """,

    version="1.0"

)


app.include_router(users_router)

app.include_router(integrations_router)

app.include_router(analytics_router)



@app.get("/")
def home():

    return {

        "platform":
        "Enterprise API Gateway",

        "status":
        "Running"

    }

Overwriting backend/main.py

In [11]:
import sys

sys.path.insert(
    0,
    "/content/backend"
)


from main import app


print("FastAPI import successful")

FastAPI import successful

In [12]:
import subprocess
import time


process = subprocess.Popen(
    [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
    ],
    cwd="/content/backend"
)


time.sleep(5)


print("Server started")

Server started

In [13]:
import requests


response = requests.get(
    "http://127.0.0.1:8000/"
)


print(response.status_code)

print(response.json())

200
{'platform': 'Enterprise API Gateway', 'status': 'Running'}

In [14]:
from google.colab import output


url = output.eval_js(
    "google.colab.kernel.proxyPort(8000)"
)


print(url)

https://8000-m-s-kkb-ase1a2-8h5k95tunzs4-a.asia-east1-2.prod.colab.dev